import numpy as np
import matplotlib.pyplot as plt

Td_min = 278.15
Td_max = 313.15
Td_ideal = 295.65

alb_barren = 0.5
alb_white = 0.75
alb_black = 0.25
area_white = 0.01
area_black = 0.01

insul = 20
drate = 0.3

# Convergence criteria
maxconv = 1000
tol = 0.000001

# Flux terms
So = 1000
sigma = 5.67032e-8

if __name__ == '__main__':
    # Initialize arrays
    fluxes = np.arange(0.5, 1.6, 0.002)
    area_black_vec = np.zeros_like(fluxes)
    area_white_vec = np.zeros_like(fluxes)
    area_barren_vec = np.zeros_like(fluxes)
    Tp_vec = np.zeros_like(fluxes)

    # Loop over fluxes
    for j, flux in enumerate(fluxes):
        # Minimum daisy coverage
        if area_black < 0.01:
            area_black = 0.01
        if area_white < 0.01:
            area_white = 0.01
        area_barren = 1 - (area_black + area_white)

        # Reset iteration metrics
        it = 0
        dA_black = 2*tol
        dA_white = 2*tol
        darea_black_old = 0
        darea_white_old = 0

        while it <= maxconv and dA_black > tol and dA_white > tol:
            # Planetary albedo
            alb_p = (area_black * alb_black
                     + area_white * alb_white
                     + area_barren * alb_barren)
            # Planetary temperature
            Tp = (flux*So*(1-alb_p)/sigma)**(1/4)
            # Local temperatures
            Td_black = insul*(alb_p-alb_black) + Tp
            Td_white = insul*(alb_p-alb_white) + Tp

            # Determine birth rates
            if (Td_black >= Td_min
                    and Td_black <= Td_max
                    and area_black >= 0.01):
                birth_black = 1 - 0.003265*(Td_ideal-Td_black)**2
            else:
                birth_black = 0.0

            if (Td_white >= Td_min
                    and Td_white <= Td_max
                    and area_white >= 0.01):
                birth_white = 1 - 0.003265*(Td_ideal-Td_white)**2
            else:
                birth_white = 0.0

            # Change in areal extents
            darea_black = area_black*(birth_black*area_barren-drate)
            darea_white = area_white*(birth_white*area_barren-drate)

            # Change from previous iteration
            dA_black = abs(darea_black-darea_black_old)
            dA_white = abs(darea_white-darea_white_old)

            # Update areas, states, and iteration count
            darea_black_old = darea_black
            darea_white_old = darea_white
            area_black = area_black+darea_black
            area_white = area_white+darea_white
            area_barren = 1-(area_black+area_white)
            it += 1

        # Save states
        area_black_vec[j] = area_black
        area_white_vec[j] = area_white
        area_barren_vec[j] = area_barren
        Tp_vec[j] = Tp

    fig, ax = plt.subplots(2, 1)
    ax[0].plot(fluxes, 100*area_black_vec, color='black', label='black')
    ax[0].plot(fluxes, 100*area_white_vec, color='red', label='white')
    ax[0].set_xlabel('solar luminosity')
    ax[0].set_ylabel('area (%)')
    plt.legend()

    ax[1].plot(fluxes, Tp_vec-273.15, color='black')
    ax[1].set_xlabel('solar luminosity')
    ax[1].set_ylabel('global temperature (C)')
    plt.savefig('WGEG.png')